### ISSUE TITLE
Bedere Readme

### ISSUE THREAD

**Issue by neic** [TK-IT/regnskab#3]
Der mangler en readme så fremtidens udviklere, også dem der ikke er så gode udviklere, kan finde finde ud af hvordan koden virker. Shameless plug: websidens [readme](https://github.com/TK-IT/web/blob/master/readme.md) og [prodekanus-readme](https://github.com/TK-IT/web/blob/master/readme-prodekanus.md) er gode.

**Comment by Mortal** [comment]
Flyttet til https://github.com/TK-IT/web/issues/191
