### ISSUE TITLE
Tydeligere fejlbesked

### ISSUE THREAD

**Issue by OEHC** [TK-IT/regnskab#33]
Hvis man i en email template skriver et forkert variabelnavn, får man følgende fejlbesked:
https://github.com/TK-IT/regnskab/blob/32ec81c5dc19f383d750f462b36fd3f07b7820b5/regnskab/models.py#L801-L802

Den kan dog let forsvinde i alt det andet, så måske den skal tydeliggøres med større og/eller rød skrift?

**Comment by Mortal** [comment]
Moved to https://github.com/TK-IT/web/issues/188
