### ISSUE TITLE
Smartere håndtering af dårlig krydsliste

### ISSUE THREAD

**Issue by tjavsi** [TK-IT/regnskab#34]
Når man har uploadet en krydsliste til opgørelse, ville det være rart at kunne slette den igen. Da man først kan se om den er skannet perfekt ind, efter man har uploadet den. 

https://www.TAAGEKAMMERET.dk/regnskab/sheet/262/edit/ er et eksempel på en som er dårlig skannet ind, hvor jeg efterfølgende går op og skanner den ind igen, for at få et bedre resultat. 
https://www.TAAGEKAMMERET.dk/regnskab/sheet/263/edit/ var så mit forsøg på at gøre det bedre, virkede lidt. Dog stadig med nogle problemer.

**Comment by tjavsi** [comment]
Tror faktisk ikke at slette en krydsliste er nok til at fikse det her problem. 

Så der skal nok være en måde at fikse en krydsliste, hvis den ikke kan skannes ind.

**Comment by Mortal** [comment]
Den pågældende krydsliste var blevet slidt i nederste venstre hjørne, så programmet kunne ikke finde det rigtige venstre hjørne-punkt. For at gøre tingene værre så bruges dette nederste venstre hjørne til at udlede hvor det øverste højre hjørne er (ud fra formlen topright = topleft + (bottomright - bottomleft)), så hjørnet øverst til højre er også galt, hvilket tydeligt ses på den højreste søjle i følgende to billeder:

* https://www.taagekammeret.dk/regnskab/sheet/262/1/proj.png
* https://www.taagekammeret.dk/regnskab/sheet/263/1/proj.png

Et manuelt fiks af det nederste venstre hjørne løste problemet for INKA denne gang:

* https://www.taagekammeret.dk/regnskab/sheet/264/1/proj.png

(login påkrævet for alle ovenstående links)

Det ville være smart hvis man kunne justere hjørnerne inden krydslisten aflæses - eller alternativt at vi bare finder en bedre måde at finde hjørnerne på.

**Comment by Mortal** [comment]
Moved to https://github.com/TK-IT/web/issues/189
