### ISSUE TITLE
Undgå utilsigtede aliasser

### ISSUE THREAD

**Issue by neic** [TK-IT/regnskab#36]
INKA kom i sidste uge til at skrive 'vc' i aliasfeltet istedet for søgefeltet. Det betyder at FORM har haft aliaset 'vc' i en dag.

- Man kunne lave en ægte slet knap, men den kan man også komme til at trykke på ved en fejl.
- Man kunne også lave dialogboks til at bekræfte tilføjelsen af et alias.
- Eller hvis et alias blev deaktiveret samme dag som det blev oprettet skulle det fjernes helt. (Rav og min umiddelbare favorit.)

**Comment by Mortal** [comment]
Lad os vælge den tredje mulighed. Flyttet til https://github.com/TK-IT/web/issues/188
